db:
  type: postgresql
  ip: 127.0.0.1
  port: 5432
  username: postgres
  password:
  database: facial_development

log:
  timestampFormat: 2006-01-02 15:04:05
  level: debug # 可以设置 "debug" "info" "warn" "error" "fatal"
  # file:
  #   path: /var/log/facial/access.log

redis:
  ip: 127.0.0.1
  port: 6379
  password:
  db: 0

server:
  port: 9000

